name: letsgotrip
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # sdk: ">=2.14.0 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  app_settings: 4.1.0

# etc
  graphql_flutter: ^5.0.0
  image_picker: ^0.8.4
  path_provider: ^2.0.4
  flutter_exif: ^1.0.1
  exif: ^3.0.0
  metadata: any
  flutter_rating_bar: ^4.0.0
  webview_flutter: any
  sign_in_with_apple: ^3.2.0
  syncfusion_flutter_datepicker: ^19.3.46
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  readmore: ^2.1.0

# google map
  fluster: ^1.2.0
  google_maps_cluster_manager: ^3.0.0+1
  geocoder: ^0.2.1
  flutter_cache_manager: ^3.1.2
  geolocator: ^7.6.2

# aws
  amplify_auth_cognito: any
  amplify_flutter: ^0.2.0
  amplify_storage_s3: ^0.2.0
  amplify_core: any
  
# common
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  flutter_native_splash: ^1.2.3
  permission_handler: ^8.1.6
  # notification_permissions: ^0.6.0
  flutter_svg: ^0.22.0
  google_maps_flutter: any
  # google_maps_flutter: ^2.0.10
  google_maps_controller: ^1.2.0
  http: ^0.13.3
  flutter_secure_storage: ^4.2.1
  device_info: ^2.0.2
  ios_utsname_ext: ^2.0.0
  package_info: ^2.0.2
  uuid: ^3.0.4
  get: ^4.3.8
  kakao_flutter_sdk: any
  flutter_naver_login: ^1.2.3
  carousel_slider: ^4.0.0
  dio: ^4.0.0 # for kakao login
  json_annotation: ^4.0.1 # for kakao login
  shared_preferences: ^2.0.5 # for kakao login
  platform: ^3.0.0 # for kakao login
  package_info_plus: ^1.0.4 # for kakao login

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/authority/
    - assets/images/walkthroughFirst/
    - assets/images/walkthroughSecond/
    - assets/images/walkthroughThird/
    - assets/images/profileSettings/
    - assets/images/locationTap/
    - assets/images/settings/
    - assets/texts/
    - assets/postal.html

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: NotoSansCJKkrBold
      fonts:
        - asset: fonts/NotoSansCJKkr-Bold.otf
    - family: NotoSansCJKkrRegular
      fonts:
        - asset: fonts/NotoSansCJKkr-Regular.otf
    - family: NotoSansMonoCJKkrBold
      fonts:
        - asset: fonts/NotoSansMonoCJKkr-Bold.otf
    - family: NotoSansMonoCJKkrRegular
      fonts:
        - asset: fonts/NotoSansMonoCJKkr-Regular.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#FFFFFF"
  # background_image: "assets/images/splash.png"
  
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing 
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a 
  # png file and should be sized for 4x pixel density.
  image: "assets/images/splash_logo.png"

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or 
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given 
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see 
  # https://developer.android.com/reference/android/view/Gravity): bottom, center, 
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see 
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill, 
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight, 
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web 
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true
  
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) 
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  #android12: true
